spring.application.name=road-helper

spring.datasource.url=jdbc:postgresql://localhost:5432/mananc
spring.datasource.username=mananc
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

app.jwt.secret=mySecretKeyForJWTSigningThatIsAtLeast256BitsLongForHS256Algorithm123456
app.jwt.expiration-ms=86400000
app.jwt.guest-expiration-ms=14400000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect