[road_helper_servers]
target_node ansible_host=127.0.0.1 ansible_connection=local

[road_helper_servers:vars]
app_name=road-helper
app_port=8080
db_port=5432
db_user=mananc
db_password=password123
db_name=roadhelper_db
war_path=target/road-helper-0.0.1-SNAPSHOT.war
docker_image=mananch1/road-helper:latest
deploy_mode=container
